# fly.toml app configuration file generated for znightscout on 2025-03-03T21:08:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'znightscout'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
